require("core.plugin_config.neosolarized")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.nvim-cmp-config")
require("core.plugin_config.bufferline")
require("core.plugin_config.lsp.server")
require("core.plugin_config.lsp.mason")
require("core.plugin_config.lsp.nulls")
-- require("core.plugin_config.lsp.saga")
